name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -f ./Dockerfile -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/node-app:latest .
          docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/node-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kubernetes Manifests Repo
        uses: actions/checkout@v3
        with:
          repository: Mason-P-ark/k8s-manifests
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Kubernetes Deployment Image
        run: |
          sed -i 's|image: ghcr.io/.*/node-app:.*|image: ghcr.io/${{ secrets.DOCKER_USERNAME }}/node-app:latest|' deployment.yaml
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Update deployment image"
          git push
